# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcertificate',
            name='serial_number',
            field=models.IntegerField(default=1, help_text=b'Serial number of the certificate'),
            preserve_default=False,
        ),
    ]
