# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_sslcertificate_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcertificationauthority',
            name='revocation_list',
            field=models.TextField(blank=True, default=b'', help_text=b'Revocation list of the certificate'),
        ),
    ]
