# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_sslcertificationauthority_revocation_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcertificate',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
