# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_sslcertificate_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcertificaterequest',
            name='status',
            field=models.CharField(blank=True, choices=[(b'GENERATING', b'Generating'), (b'VALIDATING', b'Waiting to be signed'), (b'DECLINED', b'The certificate request was declined'), (b'SIGNING', b'Signing'), (b'SIGNED', b'Signed'), (b'FAILED', b'Failed to be signed')], default=b'GENERATING', max_length=32),
        ),
    ]
