# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_auto_20160124_0900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sslrevokedcertificate',
            unique_together=set([('certification_authority', 'serial_number')]),
        ),
    ]
