# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_auto_20160124_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcertificate',
            name='status',
            field=models.CharField(blank=True, choices=[(b'CREATING', b'Creating'), (b'VALID', b'Valid'), (b'REVOKED', b'Revoked'), (b'EXPIRED', b'Expired')], default=b'CREATING', max_length=32),
        ),
    ]
