# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160116_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sshpubkey',
            options={'verbose_name': 'SSH public key', 'verbose_name_plural': 'SSH public keys'},
        ),
    ]
